.ng:lint:
    stage: Testing and building modules
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    script:
        - make -f /opt/makefiles/Makefile.angular lint
    except:
        variables:
            - $IGNORE_LINT
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:test:
    stage: Testing and building modules
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    variables:
        REPORTERS: junit,spec,kjhtml
        BROWSERS: WebDriverChrome
        NODE_OPTIONS: --max-old-space-size=2560
        SELENIUM_HOST: selenium-hub
        SELENIUM_PORT: 4444
        HUB_HOST: selenium-hub
    services:
        - name: selenium/hub:latest
          alias: selenium-hub
        - name: selenium/node-firefox:latest
        - name: selenium/node-chrome:latest
    before_script:
        - npm run ci:test:before_script --if-present
    script:
        - make -f /opt/makefiles/Makefile.angular test
    after_script:
        - npm run ci:test:after_script --if-present
        - make -f /opt/makefiles/Makefile.coverage
    coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
    artifacts:
        reports:
            junit:
                - junit-report/TESTS*.xml
        expire_in: 30 days
        when: always
        paths:
            - coverage/
    except:
        variables:
            - $IGNORE_TESTS
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:e2e:
    stage: Testing and building modules
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    before_script:
        - npm run ci:e2e:before_script --if-present
    script:
        - make -f /opt/makefiles/Makefile.angular e2e
    after_script:
        - npm run ci:e2e:after_script --if-present
    artifacts:
        expire_in: 30 days
        when: always
        paths:
            - coverage/
            - dist/e2e/${PROJECT_NAME:-${CI_PROJECT_NAME}}/
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:build:
    stage: Testing and building modules
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    dependencies: []
    variables:
        NODE_OPTIONS: --max-old-space-size=2560
    before_script:
        - npm run ci:build:before_script --if-present
    script:
        - make -f /opt/makefiles/Makefile.angular build
    after_script:
        - npm run ci:build:after_script --if-present
    artifacts:
        expire_in: 30 days
        paths:
            - dist/${PROJECT_NAME:-${CI_PROJECT_NAME}}/
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:lint:general:
    extends:
        - .ng:lint
        - .general-environment

.ng:lint:develop:
    extends:
        - .ng:lint
        - .develop-environment

.ng:lint:test:
    extends:
        - .ng:lint
        - .test-environment

.ng:lint:stage:
    extends:
        - .ng:lint
        - .stage-environment

.ng:lint:production:
    extends:
        - .ng:lint
        - .production-environment

.ng:test:general:
    extends:
        - .ng:test
        - .general-environment

.ng:test:develop:
    extends:
        - .ng:test
        - .develop-environment

.ng:test:test:
    extends:
        - .ng:test
        - .test-environment

.ng:test:stage:
    extends:
        - .ng:test
        - .stage-environment

.ng:test:production:
    extends:
        - .ng:test
        - .production-environment

.ng:e2e:general:
    extends:
        - .ng:e2e
        - .general-environment
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:e2e:develop:
    extends:
        - .ng:e2e
        - .develop-environment
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:e2e:test:
    extends:
        - .ng:e2e
        - .test-environment
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:e2e:stage:
    extends:
        - .ng:e2e
        - .stage-environment
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:e2e:production:
    extends:
        - .ng:e2e
        - .production-environment
    except:
        variables:
            - $IGNORE_E2E
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.ng:build:general:
    extends:
        - .ng:build
        - .general-environment

.ng:build:develop:
    extends:
        - .ng:build
        - .develop-environment

.ng:build:test:
    extends:
        - .ng:build
        - .test-environment

.ng:build:stage:
    extends:
        - .ng:build
        - .stage-environment

.ng:build:production:
    extends:
        - .ng:build
        - .production-environment
