.ng:lint:
    stage: Testing and building modules
    image: node:lts-alpine
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    script:
        - $(npm bin)/ng lint ${PROJECT_NAME}
    except:
        variables:
            - $SKIP_LINT == true

.ng:test:
    stage: Testing and building modules
    image: registry.gitlab.com/savushkin.i/environment/chromium:alpine
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    variables:
        REPORTERS: junit,spec,kjhtml
        BROWSERS: ChromiumHeadlessNoSandbox
    retry:
        max: 2
        when:
            - always
    before_script:
        - npm run ci:test:before_script --if-present
    script:
        - $(npm bin)/ng test ${PROJECT_NAME} --browsers=${BROWSERS} --reporters ${REPORTERS} --watch=false --code-coverage
    after_script:
        - npm run ci:test:after_script --if-present
    coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
    artifacts:
        reports:
            junit:
                - junit-report/TESTS*.xml
        expire_in: 30 days
        when: always
        paths:
            - coverage/
    except:
        variables:
            - $SKIP_TEST == true

.ng:build:
    stage: Testing and building modules
    image: node:lts-alpine
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    dependencies: []
    retry:
        max: 2
        when:
            - always
    before_script:
        - npm run ci:build:before_script --if-present
    script:
        - $(npm bin)/ng build ${PROJECT_NAME} --prod --configuration=${PROJECT_CONFIGURATION}
    after_script:
        - npm run ci:build:after_script --if-present
    artifacts:
        expire_in: 30 days
        paths:
            - dist/${PROJECT_NAME}/

.ng:lint:general:
    extends:
        - .ng:lint
        - .general-environment

.ng:lint:develop:
    extends:
        - .ng:lint
        - .develop-environment

.ng:lint:test:
    extends:
        - .ng:lint
        - .test-environment

.ng:lint:stage:
    extends:
        - .ng:lint
        - .stage-environment

.ng:lint:production:
    extends:
        - .ng:lint
        - .production-environment

.ng:test:general:
    extends:
        - .ng:test
        - .general-environment

.ng:test:develop:
    extends:
        - .ng:test
        - .develop-environment

.ng:test:test:
    extends:
        - .ng:test
        - .test-environment

.ng:test:stage:
    extends:
        - .ng:test
        - .stage-environment

.ng:test:production:
    extends:
        - .ng:test
        - .production-environment

.ng:build:general:
    extends:
        - .ng:build
        - .general-environment

.ng:build:develop:
    extends:
        - .ng:build
        - .develop-environment

.ng:build:test:
    extends:
        - .ng:build
        - .test-environment

.ng:build:stage:
    extends:
        - .ng:build
        - .stage-environment

.ng:build:production:
    extends:
        - .ng:build
        - .production-environment
