.docker:image:build-and-publish:
    stage: Build and publish artifacts
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u ${DOCKER_REGISTRY_USERNAME:-gitlab-ci-token} -p ${DOCKER_REGISTRY_PASSWORD:-${CI_BUILD_TOKEN}} ${DOCKER_REGISTRY_URL:-${CI_REGISTRY}}
        - cd ${BUILD_CONTEXT:-.}
    after_script:
        - docker logout ${DOCKER_REGISTRY_URL:-${CI_REGISTRY}}
    script:
        - |
            IMAGE=${IMAGE_NAME:-$CI_REGISTRY_IMAGE}
            TAG=${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"}
            TAG_LATEST=${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}"}-latest
            docker build $DOCKER_BUILD_ARGS -t $IMAGE:$TAG -t $IMAGE:$TAG_LATEST .
            docker push $IMAGE:$TAG
            docker push $IMAGE:$TAG_LATEST

.docker:image:build-and-publish:general:
    extends:
        - .docker:image:build-and-publish
        - .general-environment

.docker:image:build-and-publish:develop:
    extends:
        - .docker:image:build-and-publish
        - .develop-environment

.docker:image:build-and-publish:test:
    extends:
        - .docker:image:build-and-publish
        - .test-environment

.docker:image:build-and-publish:stage:
    extends:
        - .docker:image:build-and-publish
        - .stage-environment

.docker:image:build-and-publish:production:
    extends:
        - .docker:image:build-and-publish
        - .production-environment
