.docker:image:build-and-publish:
    stage: Build and publish artifacts
    image: registry.gitlab.com/savushkin.i/environment/builder:alpine
    services:
        - docker:dind
    variables:
        DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME:-${CI_REGISTRY_USER}}
        DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD:-${CI_REGISTRY_PASSWORD}}
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL:-${CI_REGISTRY}}
        DOCKER_BUILD_PATH: ${BUILD_CONTEXT:-.}
        DOCKER_BUILD_ARGS: ${DOCKER_BUILD_ARGS}
        DOCKER_IMAGE_NAME: ${IMAGE_NAME:-${CI_REGISTRY_IMAGE}}
        DOCKER_IMAGE_TAG: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"}
        DOCKER_IMAGE_TAG_LATEST: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}"}-latest
    before_script:
        - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY_URL"
    script:
        - docker build $DOCKER_BUILD_ARGS -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG_LATEST" "$DOCKER_BUILD_PATH"
        - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
        - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG_LATEST"
    after_script:
        - docker logout "$DOCKER_REGISTRY_URL"
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.docker:image:build-and-publish:general:
    extends:
        - .docker:image:build-and-publish
        - .general-environment

.docker:image:build-and-publish:develop:
    extends:
        - .docker:image:build-and-publish
        - .develop-environment

.docker:image:build-and-publish:test:
    extends:
        - .docker:image:build-and-publish
        - .test-environment

.docker:image:build-and-publish:stage:
    extends:
        - .docker:image:build-and-publish
        - .stage-environment

.docker:image:build-and-publish:production:
    extends:
        - .docker:image:build-and-publish
        - .production-environment
