.docker:image:build-and-publish:
    stage: Build and publish artifacts
    image: registry.gitlab.com/savushkin.i/environment/builder:alpine
    services:
        - docker:dind
    variables:
        CI_REGISTRY_USER: ${DOCKER_REGISTRY_USERNAME:-${CI_REGISTRY_USER}}
        CI_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD:-${CI_REGISTRY_PASSWORD}}
        CI_REGISTRY: ${DOCKER_REGISTRY_URL:-${CI_REGISTRY}}
        CI_REGISTRY_IMAGE: ${IMAGE_NAME:-$CI_REGISTRY_IMAGE}
        CI_REGISTRY_IMAGE_TAG: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"}
        CI_REGISTRY_IMAGE_TAG_LATEST: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}"}-latest
    before_script:
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        - cd ${BUILD_CONTEXT:-.}
    script:
        - docker build ${DOCKER_BUILD_ARGS} -t ${CI_REGISTRY_IMAGE}:${CI_REGISTRY_IMAGE_TAG} -t ${CI_REGISTRY_IMAGE}:${CI_REGISTRY_IMAGE_TAG_LATEST} .
        - docker push ${CI_REGISTRY_IMAGE}:${CI_REGISTRY_IMAGE_TAG}
        - docker push ${CI_REGISTRY_IMAGE}:${CI_REGISTRY_IMAGE_TAG_LATEST}
    after_script:
        - docker logout ${CI_REGISTRY}
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.docker:image:build-and-publish:general:
    extends:
        - .docker:image:build-and-publish
        - .general-environment

.docker:image:build-and-publish:develop:
    extends:
        - .docker:image:build-and-publish
        - .develop-environment

.docker:image:build-and-publish:test:
    extends:
        - .docker:image:build-and-publish
        - .test-environment

.docker:image:build-and-publish:stage:
    extends:
        - .docker:image:build-and-publish
        - .stage-environment

.docker:image:build-and-publish:production:
    extends:
        - .docker:image:build-and-publish
        - .production-environment
