.jekyll:build:
    stage: Testing and building modules
    image: jekyll/builder:4.0.0
    before_script:
        - bundle config --local path vendor/bundle
    script:
        - JEKYLL_ENV=${PROJECT_CONFIGURATION} jekyll build --source src --destination dist/${PROJECT_NAME}
    artifacts:
        expire_in: 30 days
        paths:
            - dist/${PROJECT_NAME}/

.jekyll:build:general:
    extends:
        - .jekyll:build
        - .general-environment

.jekyll:build:develop:
    extends:
        - .jekyll:build
        - .develop-environment

.jekyll:build:test:
    extends:
        - .jekyll:build
        - .test-environment

.jekyll:build:stage:
    extends:
        - .jekyll:build
        - .stage-environment

.jekyll:build:production:
    extends:
        - .jekyll:build
        - .production-environment
