.k8s:build-manifest:
    stage: Deploy artifacts
    cache: {}
    dependencies: []
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - kustomize edit set image ${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
        - cd "${CI_PROJECT_DIR}/"
    script:
        - kustomize build "k8s/overlays/${PROJECT_CONFIGURATION}" | tee manifest.yaml
        - kubectl apply --filename manifest.yaml

.k8s:build-manifest:general:
    extends:
        - .k8s:build-manifest
        - .general-environment

.k8s:build-manifest:develop:
    extends:
        - .k8s:build-manifest
        - .develop-environment

.k8s:build-manifest:test:
    when: manual
    extends:
        - .k8s:build-manifest
        - .test-environment

.k8s:build-manifest:stage:
    when: manual
    extends:
        - .k8s:build-manifest
        - .stage-environment

.k8s:build-manifest:production:
    when: manual
    extends:
        - .k8s:build-manifest
        - .production-environment
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - kustomize edit set image "${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG#"v"}"
        - cd "${CI_PROJECT_DIR}/"
