variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

Dependency installation:
    stage: Building dependency
    image: maven:3.6.3-jdk-8
    cache:
        key: ${CI_COMMIT_REF_SLUG}-maven-dependency
        paths:
            - .m2/repository
        policy: push
    script:
        - mvn dependency:go-offline
    only:
        changes:
            - pom.xml
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.java:build:
    stage: Testing and building modules
    image: maven:3.6.3-jdk-8
    cache:
        key: ${CI_COMMIT_REF_SLUG}-maven-dependency
        paths:
            - .m2/repository
        policy: pull
    before_script:
        - mvn versions:set -DnewVersion=${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
    script:
        - mvn package
    artifacts:
        expire_in: 30 days
        paths:
            - target/${PROJECT_NAME:-${CI_PROJECT_NAME}}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.jar

.java:build:general:
    extends:
        - .java:build
        - .general-environment

.java:build:develop:
    extends:
        - .java:build
        - .develop-environment

.java:build:test:
    extends:
        - .java:build
        - .test-environment

.java:build:stage:
    extends:
        - .java:build
        - .stage-environment

.java:build:production:
    extends:
        - .java:build
        - .production-environment
