Dependency installation:
    stage: Building dependency
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: push
    script:
        - make -f /opt/makefiles/Makefile.npm ci
    only:
        changes:
            - package*.json
            - .npmrc
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
