.semantic-release:npm:
    stage: Build and publish artifacts
    image: registry.gitlab.com/savushkin.i/environment/builder:alpine
    variables:
        GIT_STRATEGY: clone
        GITLAB_URL: https://${CI_SERVER_HOST}
        GIT_AUTHOR_NAME: ${GITLAB_USER_NAME}
        GIT_AUTHOR_EMAIL: ${GITLAB_USER_EMAIL}
        GIT_COMMITTER_NAME: Mishka Assistant
        GIT_COMMITTER_EMAIL: assistant@savushkin.me
        NPM_CONFIG_REGISTRY: https://${NPM_REGISTRY_URL}
        NPM_TOKEN: ${NPM_REGISTRY_TOKEN}
    cache: {}
    script:
        - semantic-release --repository-url "${CI_REPOSITORY_URL}" --branch "${RELEASE_BRANCH:-master}"
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.semantic-release:npm:general:
    extends:
        - .semantic-release:npm
        - .general-environment

.semantic-release:npm:develop:
    extends:
        - .semantic-release:npm
        - .develop-environment

.semantic-release:npm:test:
    extends:
        - .semantic-release:npm
        - .test-environment

.semantic-release:npm:stage:
    extends:
        - .semantic-release:npm
        - .stage-environment

.semantic-release:npm:production:
    extends:
        - .semantic-release:npm
        - .production-environment

.semantic-release:docker:
    stage: Build and publish artifacts
    image: registry.gitlab.com/savushkin.i/environment/builder:alpine
    variables:
        GIT_STRATEGY: clone
        GITLAB_URL: https://${CI_SERVER_HOST}
        GIT_AUTHOR_NAME: ${GITLAB_USER_NAME}
        GIT_AUTHOR_EMAIL: ${GITLAB_USER_EMAIL}
        GIT_COMMITTER_NAME: Mishka Assistant
        GIT_COMMITTER_EMAIL: assistant@savushkin.me
        DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME:-${CI_REGISTRY_USER}}
        DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD:-${CI_REGISTRY_PASSWORD}}
        DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL:-${CI_REGISTRY}}
        DOCKER_BUILD_PATH: ${BUILD_CONTEXT:-.}
        DOCKER_BUILD_ARGS: ${DOCKER_BUILD_ARGS}
        DOCKER_IMAGE_NAME: ${IMAGE_NAME:-${CI_REGISTRY_IMAGE}}
        DOCKER_IMAGE_TAG: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"}
        DOCKER_IMAGE_TAG_LATEST: ${IMAGE_TAG:-"${CI_COMMIT_REF_SLUG}"}-latest
    services:
        - docker:dind
    cache: {}
    dependencies: []
    script:
        - semantic-release --repository-url "${CI_REPOSITORY_URL}" --branch "${RELEASE_BRANCH:-master}"
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.semantic-release:docker:general:
    extends:
        - .semantic-release:docker
        - .general-environment

.semantic-release:docker:develop:
    extends:
        - .semantic-release:docker
        - .develop-environment

.semantic-release:docker:test:
    extends:
        - .semantic-release:docker
        - .test-environment

.semantic-release:docker:stage:
    extends:
        - .semantic-release:docker
        - .stage-environment

.semantic-release:docker:production:
    extends:
        - .semantic-release:docker
        - .production-environment
