.semantic-release:
    stage: Build and publish artifacts
    image: registry.gitlab.com/savushkin.i/environment/builder:latest
    variables:
        GIT_STRATEGY: clone
        GITLAB_URL: https://${CI_SERVER_HOST}
        GIT_AUTHOR_NAME: ${GITLAB_USER_NAME}
        GIT_AUTHOR_EMAIL: ${GITLAB_USER_EMAIL}
        GIT_COMMITTER_NAME: Mishka Assistant
        GIT_COMMITTER_EMAIL: assistant@savushkin.me
        NPM_CONFIG_REGISTRY: https://${NPM_REGISTRY_URL}
        NPM_TOKEN: ${NPM_REGISTRY_TOKEN}
        DOCKER_USERNAME: $CI_REGISTRY_USER
        DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD
        DOCKER_REGISTRY_URL: $CI_REGISTRY
        DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
    dependencies: []
    cache: {}
    services:
        - docker:dind
    script:
        - make -f /opt/makefiles/Makefile.semantic-release script
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.semantic-release:general:
    extends:
        - .semantic-release
        - .general-environment

.semantic-release:develop:
    extends:
        - .semantic-release
        - .develop-environment

.semantic-release:test:
    extends:
        - .semantic-release
        - .test-environment

.semantic-release:stage:
    extends:
        - .semantic-release
        - .stage-environment

.semantic-release:production:
    extends:
        - .semantic-release
        - .production-environment
