.storybook:
    stage: Build and publish artifacts
    image: node:lts-alpine
    cache:
        key: ${CI_COMMIT_REF_SLUG}-npm-dependency
        paths:
            - node_modules/
        policy: pull
    script:
        - $(npm bin)/build-storybook
    artifacts:
        paths:
            - storybook-static

.storybook:general:
    extends:
        - .storybook
        - .general-environment

.storybook:develop:
    extends:
        - .storybook
        - .develop-environment

.storybook:test:
    extends:
        - .storybook
        - .test-environment

.storybook:stage:
    extends:
        - .storybook
        - .stage-environment

.storybook:production:
    extends:
        - .storybook
        - .production-environment
