docker:image:build-and-publish:stage:nginx:
    extends: .docker:image:build-and-publish:stage
    variables:
        DOCKER_BUILD_PATH: docker-images/nginx-spa
        DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/nginx-spa
        DOCKER_IMAGE_TAG: alpine-${CI_COMMIT_SHORT_SHA}
        DOCKER_IMAGE_TAG_LATEST: latest
    only:
        changes:
            - docker-images/nginx-spa/**/*
