docker:image:build-and-publish:stage:latex:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/latex
        IMAGE_NAME: $CI_REGISTRY_IMAGE/latex
        IMAGE_TAG: ubuntu
    only:
        changes:
            - docker-images/latex/**/*
