docker:image:build-and-publish:stage:builder:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/builder
        IMAGE_NAME: $CI_REGISTRY_IMAGE/builder
        IMAGE_TAG: alpine
    only:
        changes:
            - docker-images/builder/**/*
