include:
    - local: /templates/gitlab-ci/common/stages.yml
    - local: /templates/gitlab-ci/common/environments.yml
    - local: /templates/gitlab-ci/common/docker-job-templates.yml

docker:image:build-and-publish:stage:chromium:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/chromium
        IMAGE_NAME: chromium
        IMAGE_TAG: alpine
    only:
        changes:
            - docker-images/chromium/**/*

docker:image:build-and-publish:stage:ssh-exec:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/ssh
        IMAGE_NAME: ssh
        IMAGE_TAG: alpine
    only:
        changes:
            - docker-images/ssh/**/*
