include:
    - local: /templates/gitlab-ci/job-templates/commitlint-job-templates.yml

    - local: /templates/gitlab-ci/pipeline-templates/stages.yml
    - local: /templates/gitlab-ci/pipeline-templates/environments.yml
    - local: /templates/gitlab-ci/job-templates/docker-job-templates.yml

    - local: /docker-images/builder/gitlab-ci.yml
    - local: /docker-images/latex/gitlab-ci.yml

Linting commit message:
    extends:
        - .commitlint:lint
