include:
    - local: /templates/gitlab-ci/pipeline-templates/stages.yml
    - local: /templates/gitlab-ci/pipeline-templates/environments.yml
    - local: /templates/gitlab-ci/job-templates/docker-job-templates.yml

    - local: /docker-images/builder/gitlab-ci.yml
    - local: /docker-images/chromium/gitlab-ci.yml
    - local: /docker-images/latex/gitlab-ci.yml
    - local: /docker-images/vagrant/gitlab-ci.yml

