ng:lint:library:
    extends: 
        - .ng:lint
        - .angular-library

ng:test:library:
    extends: 
        - .ng:test
        - .angular-library
    before_script:
        - make -f /opt/makefiles/Makefile.angular build
        - npm run ci:test:before_script --if-present

ng:build:library:
    extends: 
        - .ng:build
        - .angular-library
    variables:
        PROJECT_CONFIGURATION: prod

ng:push-package:general:library:
    when: manual
    dependencies:
        - ng:build:library
    extends:
        - .npm:push-package:general
        - .general-environment-defenition
        - .angular-library

ng:push-package:develop:library:
    when: manual
    dependencies:
        - ng:build:library
    extends:
        - .npm:push-package:develop
        - .develop-environment-defenition
        - .angular-library

ng:push-package:test:library:
    when: manual
    dependencies:
        - ng:build:library
    extends:
        - .npm:push-package:test
        - .test-environment-defenition
        - .angular-library

ng:push-package:stage:library:
    when: manual
    dependencies:
        - ng:build:library
    extends:
        - .npm:push-package:stage
        - .stage-environment-defenition
        - .angular-library

ng:push-package:production:library:
    when: manual
    dependencies:
        - ng:build:library
    extends:
        - .semantic-release:npm:production
        - .production-environment-defenition
        - .angular-library
