include:
    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/stages.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/environments.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/npm-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/commitlint-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/angular-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/docker-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/semantic-release-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/k8s-job-templates.yml

Linting commit message:
    extends:
        - .commitlint:lint

Linting angular application:
    extends:
        - .ng:lint
        - .angular-application

Unit testing angular application:
    extends:
        - .ng:test
        - .angular-application

General E2E Testing angular application:
    extends:
        - .ng:e2e:general
        - .angular-application

Development E2E Testing angular application:
    extends:
        - .ng:e2e:develop
        - .angular-application

Test E2E Testing angular application:
    extends:
        - .ng:e2e:test
        - .angular-application

Stage E2E Testing angular application:
    extends:
        - .ng:e2e:stage
        - .angular-application

Production E2E Testing angular application:
    extends:
        - .ng:e2e:production
        - .angular-application

General Building angular application:
    extends:
        - .ng:build:general
        - .angular-application

Development Building angular application:
    extends:
        - .ng:build:develop
        - .angular-application

Test Building angular application:
    extends:
        - .ng:build:test
        - .angular-application

Stage Building angular application:
    extends:
        - .ng:build:stage
        - .angular-application

Production Building angular application:
    extends:
        - .ng:build:production
        - .angular-application

Development Building and publishing docker image:
    dependencies:
        - Development Building angular application
    variables:
        DOCKER_BUILD_ARGS: --build-arg project=${CI_PROJECT_NAME}
    extends:
        - .docker:image:build-and-publish:develop
        - .angular-application

Test Building and publishing docker image:
    dependencies:
        - Test Building angular application
    variables:
        DOCKER_BUILD_ARGS: --build-arg project=${CI_PROJECT_NAME}
    extends:
        - .docker:image:build-and-publish:test
        - .angular-application

Stage Building and publishing docker image:
    dependencies:
        - Stage Building angular application
    variables:
        DOCKER_BUILD_ARGS: --build-arg project=${CI_PROJECT_NAME}
    extends:
        - .docker:image:build-and-publish:stage
        - .angular-application

Production Building and publishing docker image:
    dependencies:
        - Production Building angular application
    extends:
        - .semantic-release:docker:production
        - .angular-application
    variables:
        DOCKER_BUILD_ARGS: --build-arg project=${CI_PROJECT_NAME}
    when: manual

Development Deploying application:
    extends:
        - .k8s:build-manifest:develop
        - .develop-environment-defenition
        - .angular-application

Test Deploying application:
    extends:
        - .k8s:build-manifest:test
        - .test-environment-defenition
        - .angular-application

Stage Deploying application:
    extends:
        - .k8s:build-manifest:stage
        - .stage-environment-defenition
        - .angular-application

Production Deploying application:
    variables:
        DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
        DOCKER_IMAGE_TAG: ${CI_COMMIT_TAG#"v"}
    extends:
        - .k8s:build-manifest:production
        - .production-environment-defenition
        - .angular-application
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    except:
        variables: []
