include:
    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/stages.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/environments.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/npm-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/commitlint-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/angular-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/docker-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/semantic-release-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/k8s-job-templates.yml

Linting commit message:
    extends:
        - .commitlint:lint

Linting angular application:
    extends:
        - .ng:lint
        - .angular-application

Unit testing angular application:
    extends:
        - .ng:test
        - .angular-application

E2E Testing general angular application:
    extends:
        - .ng:e2e:general
        - .angular-application

E2E Testing develop angular application:
    extends:
        - .ng:e2e:develop
        - .angular-application

E2E Testing test angular application:
    extends:
        - .ng:e2e:test
        - .angular-application

E2E Testing stage angular application:
    extends:
        - .ng:e2e:stage
        - .angular-application

E2E Testing production angular application:
    extends:
        - .ng:e2e:production
        - .angular-application

Building general angular application:
    extends:
        - .ng:build:general
        - .angular-application

Building develop angular application:
    extends:
        - .ng:build:develop
        - .angular-application

Building test angular application:
    extends:
        - .ng:build:test
        - .angular-application

Building stage angular application:
    extends:
        - .ng:build:stage
        - .angular-application

Building production angular application:
    extends:
        - .ng:build:production
        - .angular-application

Building and publishing develop docker image:
    dependencies:
        - Building Develop Angular Application
    extends:
        - .docker:image:build-and-publish:develop
        - .angular-application

Building and publishing test docker image:
    dependencies:
        - Building Test Angular Application
    extends:
        - .docker:image:build-and-publish:test
        - .angular-application

Building and publishing stage docker image:
    dependencies:
        - Building Stage Angular Application
    extends:
        - .docker:image:build-and-publish:stage
        - .angular-application

Building and publishing production docker image:
    dependencies:
        - Building Production Angular Application
    extends:
        - .semantic-release:docker:production
        - .angular-application
    when: manual

Deploying develop application:
    extends:
        - .k8s:build-manifest:develop
        - .develop-environment-defenition
        - .angular-application

Deploying test application:
    extends:
        - .k8s:build-manifest:test
        - .test-environment-defenition
        - .angular-application

Deploying stage application:
    extends:
        - .k8s:build-manifest:stage
        - .stage-environment-defenition
        - .angular-application

Deploying production application:
    extends:
        - .k8s:build-manifest:production
        - .production-environment-defenition
        - .angular-application
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    except:
        variables: []
