include:
    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/stages.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/environments.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/commitlint-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/docker-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/semantic-release-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/k8s-job-templates.yml

Linting commit message:
    extends:
        - .commitlint:lint

Development Building and publishing docker image:
    extends:
        - .docker:image:build-and-publish:develop
        - .docker-application

Test Building and publishing docker image:
    extends:
        - .docker:image:build-and-publish:test
        - .docker-application

Stage Building and publishing docker image:
    extends:
        - .docker:image:build-and-publish:stage
        - .docker-application

Production Building and publishing docker image:
    extends:
        - .semantic-release:production
        - .docker-application
    when: manual

Development Deploying application:
    extends:
        - .k8s:build-manifest:develop
        - .develop-environment-defenition
        - .docker-application

Test Deploying application:
    extends:
        - .k8s:build-manifest:test
        - .test-environment-defenition
        - .docker-application

Stage Deploying application:
    extends:
        - .k8s:build-manifest:stage
        - .stage-environment-defenition
        - .docker-application

Production Deploying application:
    extends:
        - .k8s:build-manifest:production
        - .production-environment-defenition
        - .docker-application
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    except:
        variables: []
