.general-environment:
    variables:
        PROJECT_CONFIGURATION: development
    except:
        refs:
            - develop
            - /^release\/.*$/
            - master
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.develop-environment:
    variables:
        PROJECT_CONFIGURATION: development
    only:
        refs:
            - develop
    except:
        variables:
            - $RELEASE_BRANCH == "develop"
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.test-environment:
    variables:
        PROJECT_CONFIGURATION: test
    only:
        refs:
            - /^release\/.*$/
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.stage-environment:
    variables:
        PROJECT_CONFIGURATION: stage
    only:
        refs:
            - master
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/

.production-environment:
    variables:
        PROJECT_CONFIGURATION: production
    only:
        variables:
            - $RELEASE_BRANCH == $CI_COMMIT_REF_NAME
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
