.general-environment:
    variables:
        PROJECT_CONFIGURATION: development
    except:
        refs:
            - develop
            - /^release\/.*$/
            - master
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/

.develop-environment:
    variables:
        PROJECT_CONFIGURATION: development
    only:
        refs:
            - develop
    except:
        variables:
            - $RELEASE_BRANCH == "develop"

.test-environment:
    variables:
        PROJECT_CONFIGURATION: test
    only:
        refs:
            - /^release\/.*$/

.stage-environment:
    variables:
        PROJECT_CONFIGURATION: stage
    only:
        refs:
            - master

.production-environment:
    variables:
        PROJECT_CONFIGURATION: production
    only:
        variables:
            - $RELEASE_BRANCH == $CI_COMMIT_REF_NAME
