include:
    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/stages.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/pipeline-templates/environments.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/commitlint-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/maven-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/docker-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/semantic-release-job-templates.yml

    - project: savushkin.i/environment
      ref: master
      file: templates/gitlab-ci/job-templates/k8s-job-templates.yml

General Building java application:
    extends:
        - .java:build:general
        - .java-application

Development Building java application:
    extends:
        - .java:build:develop
        - .java-application

Test Building java application:
    extends:
        - .java:build:test
        - .java-application

Stage Building java application:
    extends:
        - .java:build:stage
        - .java-application

Production Building java application:
    extends:
        - .java:build:production
        - .java-application

Development Building and publishing docker image:
    dependencies:
        - Development Building java application
    variables:
        DOCKER_BUILD_ARGS: --build-arg JAR_FILE=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.jar
    extends:
        - .docker:image:build-and-publish:develop
        - .java-application

Test Building and publishing docker image:
    dependencies:
        - Test Building java application
    variables:
        DOCKER_BUILD_ARGS: --build-arg JAR_FILE=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.jar
    extends:
        - .docker:image:build-and-publish:test
        - .java-application

Stage Building and publishing docker image:
    dependencies:
        - Stage Building java application
    variables:
        DOCKER_BUILD_ARGS: --build-arg JAR_FILE=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.jar
    extends:
        - .docker:image:build-and-publish:stage
        - .java-application

Production Building and publishing docker image:
    dependencies:
        - Production Building java application
    extends:
        - .semantic-release:production
        - .java-application
    variables:
        DOCKER_BUILD_ARGS: --build-arg JAR_FILE=${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}.jar
    when: manual

Development Deploying application:
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - cat "${DEVELOPMENT_PROPERTIES}" >> ./application-development.properties
        - kustomize edit add configmap ${CI_PROJECT_NAME}-profile-configmap --from-file application-development.properties
        - kustomize edit set image ${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
        - cd "${CI_PROJECT_DIR}/"
    extends:
        - .k8s:build-manifest:develop
        - .develop-environment-defenition
        - .java-application

Test Deploying application:
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - cat "${TEST_PROPERTIES}" >> ./application-test.properties
        - kustomize edit add configmap ${CI_PROJECT_NAME}-profile-configmap --from-file application-test.properties
        - kustomize edit set image ${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
        - cd "${CI_PROJECT_DIR}/"
    extends:
        - .k8s:build-manifest:test
        - .test-environment-defenition
        - .java-application

Stage Deploying application:
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - cat "${STAGE_PROPERTIES}" >> ./application-stage.properties
        - kustomize edit add configmap ${CI_PROJECT_NAME}-profile-configmap --from-file application-stage.properties
        - kustomize edit set image ${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
        - cd "${CI_PROJECT_DIR}/"
    extends:
        - .k8s:build-manifest:stage
        - .stage-environment-defenition
        - .java-application

Production Deploying application:
    before_script:
        - cd "k8s/overlays/${PROJECT_CONFIGURATION}"
        - cat "${PRODUCTION_PROPERTIES}" >> ./application-production.properties
        - kustomize edit add configmap ${CI_PROJECT_NAME}-profile-configmap --from-file application-production.properties
        - kustomize edit set image "${CI_REGISTRY_IMAGE}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG#"v"}"
        - cd "${CI_PROJECT_DIR}/"
    extends:
        - .k8s:build-manifest:production
        - .production-environment-defenition
        - .java-application
    only:
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
    except:
        variables: []
