ts:build:library:
    extends: 
        - .ts:build
        - .typescript-library

ts:push-package:general:library:
    when: manual
    dependencies:
        - ts:build:library
    extends:
        - .npm:push-package:general
        - .general-environment-defenition
        - .typescript-library

ts:push-package:develop:library:
    when: manual
    dependencies:
        - ts:build:library
    extends:
        - .npm:push-package:develop
        - .develop-environment-defenition
        - .typescript-library

ts:push-package:test:library:
    when: manual
    dependencies:
        - ts:build:library
    extends:
        - .npm:push-package:test
        - .test-environment-defenition
        - .typescript-library

ts:push-package:stage:library:
    when: manual
    dependencies:
        - ts:build:library
    extends:
        - .npm:push-package:stage
        - .stage-environment-defenition
        - .typescript-library

ts:push-package:production:library:
    when: manual
    dependencies:
        - ts:build:library
    extends:
        - .semantic-release:npm:production
        - .production-environment-defenition
        - .typescript-library
