.ssh-deploy:
    stage: Deploy artifacts
    cache: {}
    dependencies: []
    image: registry.gitlab.com/savushkin.i/environment/ssh:alpine
    before_script:
        - eval $(ssh-agent -s)
        - echo "$DEPLOY_KEY" | ssh-add - > /dev/null
        - ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        - ssh $DEPLOY_USER@$DEPLOY_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    after_script:
        - ssh $DEPLOY_USER@target-rus.ru "docker logout $CI_REGISTRY"

.ssh-deploy:general:
    extends:
        - .ssh-deploy
        - .general-environment

.ssh-deploy:develop:
    extends:
        - .ssh-deploy
        - .develop-environment

.ssh-deploy:test:
    extends:
        - .ssh-deploy
        - .test-environment

.ssh-deploy:stage:
    extends:
        - .ssh-deploy
        - .stage-environment

.ssh-deploy:production:
    extends:
        - .ssh-deploy
        - .production-environment
