docker:image:build-and-publish:stage:chromium:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/chromium
        DOCKER_REGISTRY_USERNAME: gitlab-ci-token
        DOCKER_REGISTRY_PASSWORD: $CI_BUILD_TOKEN
        DOCKER_REGISTRY_URL: $CI_REGISTRY
        IMAGE_NAME: $CI_REGISTRY_IMAGE/chromium
        IMAGE_TAG: alpine
    only:
        changes:
            - docker-images/chromium/**/*
