docker:image:build-and-publish:stage:chromium:
    extends: .docker:image:build-and-publish:stage
    variables:
        BUILD_CONTEXT: docker-images/chromium
        IMAGE_NAME: $CI_REGISTRY_IMAGE/chromium
        IMAGE_TAG: alpine
    only:
        changes:
            - docker-images/chromium/**/*
