PROJECT_NAME?=${CI_PROJECT_NAME}

all: ci

ci:
	npm ci
ifeq ($(shell test -e $(shell npm bin)/ngcc && echo -n yes),yes)
	$$(npm bin)/ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
endif

.PHONY: ci
