DOCKER_BUILD_PATH?=.

all: login build logout

login:
	docker login -u "${DOCKER_USERNAME}" -p "$$DOCKER_PASSWORD" "${DOCKER_REGISTRY_URL}"

build: IMAGE=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
build: IMAGE_LATEST=${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG_LATEST}
build:
	docker build ${DOCKER_BUILD_ARGS} -t "${IMAGE}" -t "${IMAGE_LATEST}" "${DOCKER_BUILD_PATH}"
	docker push "${IMAGE}"
	docker push "${IMAGE_LATEST}"

logout:
	docker logout "${DOCKER_REGISTRY_URL}"

.PHONY: login build logout
