PROJECT_NAME?=${CI_PROJECT_NAME}

script: node_modules

node_modules: package.json package-lock.json
	npm ci

after_script: ngcc

ngcc:
ifeq ($(shell test -e $(shell npm bin)/ngcc && echo -n yes),yes)
	$$(npm bin)/ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
endif

.PHONY: script after_script ngcc
